# Generated by Django 4.0.4 on 2022-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_category_options_alter_postcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categoryType',
            field=models.CharField(choices=[('News', 'Новость'), ('Article', 'Статья')], default='Article', max_length=10),
        ),
    ]
