# Generated by Django 4.0.4 on 2022-05-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
